### ISSUE TITLE
Beta Testers Needed!  Especially for Windows!

### ISSUE THREAD

**Issue by CleanCut** [CleanCut/rusty_sword_arena#1]
I need some beta testers well before OSCON 2018 to help make sure that things will work somewhere other than my own laptop!  _Anyone willing can be a tester.  You don't even have to come to OSCON!_

I especially need **windows** beta testers, because I don't do windows. 😉

**If you are willing to be a tester, please leave a comment below!!!**

**Comment by hprinter** [comment]
Beta Testing is one such methodology which allows the users to experience the product before it reaches the market. for more information visit here 

https://hpetechnicalsupportnumber.com/fix-hp-printer-error-code-messages/
--
