### ISSUE TITLE
Rusty Sword Arena - The Online Course

### ISSUE THREAD

**Issue by CleanCut** [CleanCut/rusty_sword_arena#2]
The half-day OSCON tutorial was a blast. I'm going to adapt the tutorial to an online course format. If you want a free code, or if you'd like participate (be an early reviewer, etc.), then tell me in a comment below.

If you'd just like to see when the courses go live, then hit "subscribe" over there -->>

---
(This section will be updated with links to the online courses as they go live)
- [ ] Udemy: ...
- [ ] Skillshare: ...
- [ ] (Maybe PluralSight? Need to audition...)
(If you'd like to see this on some other site, please let me know)

**Comment by schreck61** [comment]
I enjoyed the tutorial very much!  Count me in!

**Comment by edziegle** [comment]
The tutorial and the subsequent after-hours followup were a blast. I’d love to help out.

**Comment by CleanCut** [comment]
After a month away, I'm ready to get going on this!

I have started started putting together the skeleton of the online course, and hope to start producing some of the video content soon.  Nothing to see there, yet, though.

@schreck61 @edziegle If you're interested in helping out in the code side of things, there are two big changes that I would love to make to the underlying `rusty_sword_arena` crate: [Replace glium (OpenGL subsystem)](https://github.com/CleanCut/rusty_sword_arena/issues/5) and [New Audio Subsystem](https://github.com/CleanCut/rusty_sword_arena/issues/4)

**Comment by CleanCut** [comment]
Quick update: I got very, very distracted by some personal life events.  I hope to get back to this soon.  What does that mean?  Well, the holidays usually go one of two ways for me.  Either I end up working on projects a ton, or I don't work on them at all.  So I should be hitting this hard either starting next week...or next January. 😉

**Comment by CleanCut** [comment]
A couple of relevant news items:

### Rusty Sword Arena was accepted for [OSCON 2019](https://conferences.oreilly.com/oscon/oscon-or/public/schedule/detail/75769)! 🎉 
  - This will be updated to use the Rust 2018 edition.
  - I plan to overhaul the networking
  - I also need to remove...something and/or simplify. We've got about 2 hours too much content as is (unfortunately they rejected my 2-part proposal for taking a whole day, which would have let me *expand* the content instead).
  - If I'm able to accomplish all of that and still have time, I'll work on replacing the OpenGL backend with a Vulkan backend.
  - And/or if I still have time I may work on recording this as I originally intended last year (I really should have just done it right before or after the conference last year when I was all prepped and ready)

### I will be teaching a LIVE "Rust Programming: A Crash Course" on O'Reilly Safari online
- [March 27th](https://learning.oreilly.com/live-training/courses/rust-programming-a-crash-course/0636920260431/) and [May 22nd](https://learning.oreilly.com/live-training/courses/rust-programming-a-crash-course/0636920266013/) this year are the sessions that are scheduled so far -- come and join us if you want!
- It has similar instructional content to Rusty Sword Arena, but...
- Without any of the fun, thematic stuff, game engine stuff. (They told me something like "This is a business environment. Let's remove the hyperbole") 
- Which is why I'm spending this weekend figuring out a good way to still engage people (that I can't see, because this is a 1-way video thing) without too much "hyperbole" but still avoiding boring people to death.

**Comment by CleanCut** [comment]
# [Ultimate Rust Crash Course](https://agileperception.com/ultimate_rust_crash_course)!

I _**finally**_ published a prerecorded, online version of the lectures from this course (only updated and expanded). My [Ultimate Rust Crash Course](https://agileperception.com/ultimate_rust_crash_course) page on my website lists the places you can consume it.

Please use the links on the page above if you plan to purchase the course -- they are direct referral links that get me a higher royalty.  If folks who have ever attended any of my courses in the past would like free or discounted access, please let me know and I'll see what I can do to accommodate as many as you as possible.

For those generous souls among you (or those who have training budgets through work) who want to support my Rust efforts, please purchase one of my courses through the links on the page above, or [sponsor my Rust efforts on GitHub](https://github.com/sponsors/CleanCut)!

**Comment by CleanCut** [comment]
Oh! I almost forgot to mention, as I prepare to teach my first _full day_ of training for OSCON 2020, I will be expanding some lectures and adding others -- I will add those to the course as I create them.

I also plan to add project run through's (Rusty Sword, Rusty Sword Arena, and the yet-to-be-created Rusty Racing)
