### ISSUE TITLE
New Audio Subsystem

### ISSUE THREAD

**Issue by CleanCut** [CleanCut/rusty_sword_arena#4]
We need a new audio subsystem.  The issue I have with the current one ([impose](https://crates.io/crates/impose)) is that sounds cannot overlap.

Required attributes:
- [x] Supported on Mac, Linux, and Windows
- [x] Sounds can overlap
- [x] Plays mp3 or ogg files

Then optimize for
- [x] Least dependencies need to be installed

Here are two options that I am aware of (but there may be a better option out there)
- [ears](https://crates.io/crates/ears) - Has the required functionality. Requires installing 2 dependencies on mac/linux, 1 dependency on windows.
- [rodio](https://crates.io/crates/) - The low-level library behind `impose`.  We would have to write our own impose-like audio system to expose to students, because the details of low-level audio handling is beyond the scope of the crash course. Requires installing 1 dependency on Linux, 0 dependencies on Mac/Windows.

**Comment by edziegle** [comment]
I've been thinking over solutions for this today. `ears` seems to be the most straightforward way into this, with the caveat of those two deps. We could try to abstract away the dependency install via an external tool like a Makefile, or just assume users will parse the README. 🙂

In the past I've used the SDL2 library for game engine programming, and it appears someone has made [Rust bindings](https://github.com/Rust-SDL2/rust-sdl2) for it. SDL2's `mixer` component would do what we need. As far as I know this would require one dependency: SDL2 itself (I believe the Steam client installs this dep which could save folks effort).

I read that Chucklefish (makers of Starbound) are developing a game in Rust using this SDL2 binding library, and a few on their team have contributed to it. But thats kind of a can-of-worms where we are bringing in a C library to do work that maybe we'd rather do with Rust.

**Comment by CleanCut** [comment]
@edziegle I'd rather depend on the README than a Makefile, for sure. 🙂 

`ears` is definitely a contender -- I've used it before.  `rust-sdl2` sounds interesting, If it's a single dependency to install then it _could_ be a better fit than `ears`.  I'm really intrigued by `rodio`, though.  Only 1 dependency just on Linux.  `impose` is just a single 101-line crate using `rodio`. I'm really wondering about either submitting a PR to `impose` to add mixing support, or just writing my own impose-like library.

You seem most interested in `rust-sdl2`.  If you want to give it a shot, I'd be happy to work with you on that.

**Comment by CleanCut** [comment]
Or if you would like to collaborate on a `rodio`-based solution, I'd be up for that as well.

**Comment by CleanCut** [comment]
✅ Done.  I rewrote the audio subsystem to use rodio directly.
